// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2hwvPzisaFYzq7wndvzhef6eiH5tKo4c',
    appId: '1:701431148668:web:351e606674825da08c99f9',
    messagingSenderId: '701431148668',
    projectId: 'flutter-autoput2',
    authDomain: 'flutter-autoput2.firebaseapp.com',
    storageBucket: 'flutter-autoput2.appspot.com',
    measurementId: 'G-9CNTHX1R1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1maQ7iV45FydvFUbQeV92OLNDFP3ZI8',
    appId: '1:701431148668:android:fa5a95ab657e53a58c99f9',
    messagingSenderId: '701431148668',
    projectId: 'flutter-autoput2',
    storageBucket: 'flutter-autoput2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMHOY6oZlM8Eo6icn-ciQ5E8OaEbO1Ao',
    appId: '1:701431148668:ios:a6aabb2a5528db7b8c99f9',
    messagingSenderId: '701431148668',
    projectId: 'flutter-autoput2',
    storageBucket: 'flutter-autoput2.appspot.com',
    iosBundleId: 'com.example.flutterAutoput2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMHOY6oZlM8Eo6icn-ciQ5E8OaEbO1Ao',
    appId: '1:701431148668:ios:bd1cc24d31265fba8c99f9',
    messagingSenderId: '701431148668',
    projectId: 'flutter-autoput2',
    storageBucket: 'flutter-autoput2.appspot.com',
    iosBundleId: 'com.example.flutterAutoput2.RunnerTests',
  );
}
